version: "3"
services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - RUN_DB_POPULATION=true
      - FLASK_ENV=development
      - DEBUG=true
    entrypoint: "flask run --host=0.0.0.0 --debug"
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
  redis:
    image: redis:latest
    ports:
      - 6379:6379